### ISSUE TITLE
Unused import of Store is not correctly considered

### ISSUE THREAD

**Issue by jase88** [fastAstortoise/ngxs-migrate#1]
Hi,

first of thanks for this great schematic!

One problem I encountered for the following file:
```typescript
import { Component } from '@angular/core';
import { Observable } from 'rxjs';
import { Select, Store } from '@ngxs/store';
import { AccountInformation } from './account-information';
import { OrganizationState } from '@store/organization.state';

@Component({
  selector: 'app-account-administration',
  templateUrl: './account-administration.component.html'
})
export class AccountAdministrationComponent {
  @Select(OrganizationState.organizationAccounts)
  accounts$: Observable<AccountInformation[]>;
}
```

> Identifier expected. (22:53)
>   20 | export class AccountAdministrationComponent {
>   21 |
> > 22 |  accounts$: Observable<AccountInformation[]> = this..select(OrganizationState.organizationAccounts);

The problem was that `Store` was imported, but never used. After removal of the unused import everything worked as expected.

Not a big issue in my case, but might be a problem for others with many unused imports.

**Comment by fastAstortoise** [comment]
Thanks for reporting. Now running the remove declarations before running migration to avoid having more checks and probably best for the code base too. since its gonna remove unused stuff.
